# Validate Story Workflow
name: validate-story
description: 'Validates a drafted story meets quality standards before being marked ready for development. Checks source document coverage, AC quality, task mapping, and previous story continuity.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
base_output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
date: system-generated

# Federated entity detection (Five Entity Types model)
detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
manifest_file: '{project-root}/docs/manifest.yaml'

# Entity-resolved paths (populated by detect-entity-type task)
entity_type: '' # Detected: constitution, infrastructure_module, strategic_container, coordination_unit, business_module
output_folder_resolved: '' # e.g., "docs/platform/core-api/" or "docs/strategy/pulse/dashboard/"
parent_output_folder: '' # Parent entity path for inheritance chain

# Sprint artifacts at entity level
sprint_artifacts: '{output_folder_resolved}sprint-artifacts'
sprint_status: '{sprint_artifacts}/sprint-status.yaml'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/4-implementation/validate-story'
instructions: '{installed_path}/instructions.md'
checklist: '{installed_path}/checklist.md'

variables:
  story_dir: '{sprint_artifacts}'
  story_file: '' # Explicit story path; auto-discovered if empty
  tech_spec_search_dir: '{output_folder_resolved}'
  tech_spec_glob_template: 'tech-spec-epic-{{epic_num}}*.md'

  # Entity-aware document search (entity + parent chain)
  doc_search_dirs: |
    - "{output_folder_resolved}"
    - "{parent_output_folder}"
    - "{base_output_folder}/platform/"

  # Validation thresholds
  critical_threshold: 0 # Any critical issues = FAIL
  major_threshold: 3 # More than 3 major issues = FAIL

  # Output options
  auto_improve: false # If true, automatically improve story on validation failure
  generate_report: true # Generate validation report file

# Smart input file references
input_file_patterns:
  epics:
    description: 'Epic containing this story'
    whole: '{output_folder_resolved}*epic*.md'
    sharded_index: '{output_folder_resolved}*epic*/index.md'
    sharded_single: '{output_folder_resolved}*epic*/epic-{{epic_num}}.md'
    load_strategy: 'SELECTIVE_LOAD'
  tech_spec:
    description: 'Technical specification for this epic'
    whole: '{output_folder_resolved}tech-spec*.md'
    sharded: '{sprint_artifacts}/tech-spec-epic-*.md'
    load_strategy: 'SELECTIVE_LOAD'
  architecture:
    description: 'System architecture and decisions'
    whole: '{output_folder_resolved}*architecture*.md'
    parent_fallback: '{parent_output_folder}*architecture*.md'
    load_strategy: 'FULL_LOAD'
  prd:
    description: 'Product requirements'
    whole: '{output_folder_resolved}*prd*.md'
    parent_fallback: '{parent_output_folder}*prd*.md'
    load_strategy: 'FULL_LOAD'

standalone: true
