# Product Requirements Document (PRD) Workflow
name: prd
description: 'Unified PRD workflow for BMad Method and Enterprise Method tracks. Produces strategic PRD and tactical epic breakdown. Hands off to architecture workflow for technical design. Note: Quick Flow track uses tech-spec workflow.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
project_name: '{config_source}:project_name'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
user_skill_level: '{config_source}:user_skill_level'
date: system-generated

# Federated hierarchy support
# Agents set {output_folder_resolved} via level-selection.xml based on user's chosen level:
#   Level 0 (System): docs/
#   Level 1 (Category): docs/{category}/
#   Level 2 (Subcategory): docs/{category}/{subcategory}/
#   Level 3 (Module): docs/{category}/{subcategory}/{module}/
# If not set by agent, workflow will prompt user or default to {output_folder}
output_folder_resolved: '{output_folder_resolved}'
constitution_path: '{constitution_path}'
current_level: '{current_level}'
current_level_name: '{current_level_name}'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/2-plan-workflows/prd'
instructions: '{installed_path}/instructions.md'

# Templates
prd_template: '{installed_path}/prd-template.md'

# Data files for data-driven behavior
project_types_data: '{installed_path}/project-types.csv'
domain_complexity_data: '{installed_path}/domain-complexity.csv'

# Output files
# Uses {output_folder_resolved} for level-aware output (set by agent via level-selection.xml)
status_file: '{output_folder}/bmm-workflow-status.yaml'
default_output_file: '{output_folder_resolved}/prd.md'

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: How to load sharded documents (FULL_LOAD, SELECTIVE_LOAD, INDEX_GUIDED)
input_file_patterns:
  product_brief:
    description: 'Product vision and goals (optional)'
    whole: '{output_folder}/*brief*.md'
    sharded: '{output_folder}/*brief*/index.md'
    load_strategy: 'FULL_LOAD'

  research:
    description: 'Market or domain research (optional)'
    whole: '{output_folder}/*research*.md'
    sharded: '{output_folder}/*research*/index.md'
    load_strategy: 'FULL_LOAD'

  document_project:
    description: 'Brownfield project documentation (optional)'
    sharded: '{output_folder}/index.md'
    load_strategy: 'INDEX_GUIDED'

standalone: true
