name: sprint-planning
description: "Generate and manage the sprint status tracking file for Phase 4 implementation, extracting all epics and stories from epic files and tracking their status through the development lifecycle"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
base_output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Federated entity detection (Five Entity Types model)
# Uses detect-entity-type task to resolve paths for any entity depth
detect_entity_task: "{project-root}/.bmad/bmm/tasks/detect-entity-type.xml"
manifest_file: "{project-root}/docs/manifest.yaml"

# Entity-resolved paths (populated by detect-entity-type task)
# Supports: Constitution, Infrastructure Module, Strategic Container, Coordination Unit, Business Module
entity_type: "" # Detected: constitution, infrastructure_module, strategic_container, coordination_unit, business_module
output_folder_resolved: "" # e.g., "docs/platform/core-api/" or "docs/strategy/pulse/dashboard/"
parent_output_folder: "" # Parent entity path for coordination sprints

# Sprint artifacts location rules (per federated model):
# - Module sprints: {entity_path}/sprint-artifacts/
# - Coordination sprints: At lowest common ancestor level
# - System sprints: docs/platform/sprint-artifacts/
sprint_artifacts: "{output_folder_resolved}sprint-artifacts"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/4-implementation/sprint-planning"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/sprint-status-template.yaml"
validation: "{installed_path}/checklist.md"

# Variables and inputs
variables:
  # Project identification
  project_name: "{config_source}:project_name"

  # Tracking system configuration
  tracking_system: "file-system" # Options: file-system, Future will support other options from config of mcp such as jira, linear, trello
  story_location: "{sprint_artifacts}" # Relative path for file-system
  story_location_absolute: "{sprint_artifacts}" # Absolute path for file operations

  # Source files (file-system only) - entity-scoped
  epics_location: "{output_folder_resolved}" # Directory containing epic*.md files
  epics_pattern: "epic*.md" # Pattern to find epic files

  # Hierarchical status file locations
  status_file: "{sprint_artifacts}/sprint-status.yaml"
  parent_status_file: "{parent_output_folder}sprint-artifacts/sprint-status.yaml"
  system_status_file: "{base_output_folder}/platform/sprint-artifacts/sprint-status.yaml"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: FULL LOAD - sprint planning needs ALL epics to build complete status
# Uses output_folder_resolved from detect-entity-type task (Five Entity Types model)
input_file_patterns:
  epics:
    description: "All epics with user stories"
    whole: "{output_folder_resolved}*epic*.md"
    sharded: "{output_folder_resolved}*epic*/*.md"
    load_strategy: "FULL_LOAD"

# Output configuration
default_output_file: "{status_file}"

standalone: true
