# Architecture Amendment Router
name: amend-architecture
description: 'Router for architecture amendment - detects entity type and dispatches to system or domain workflow.'
author: 'BMad'

config_source: '{project-root}/.bmad/bmm/config.yaml'
user_name: '{config_source}:user_name'
date: system-generated

detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
system_amend_workflow: '{project-root}/.bmad/bmm/workflows/3-solutioning/amend-system-architecture/workflow.yaml'
domain_amend_workflow: '{project-root}/.bmad/bmm/workflows/3-solutioning/amend-domain-architecture/workflow.yaml'

installed_path: '{project-root}/.bmad/bmm/workflows/3-solutioning/amend-architecture'
instructions: '{installed_path}/instructions.md'

template: false
standalone: true
