# Review Story Workflow
name: code-review
description: 'Perform a Senior Developer code review on a completed story flagged Ready for Review, leveraging story-context, epic tech-spec, repo docs, MCP servers for latest best-practices, and web search as fallback. Appends structured review notes to the story.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
base_output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
user_skill_level: '{config_source}:user_skill_level'
document_output_language: '{config_source}:document_output_language'
date: system-generated

# Federated entity detection (Five Entity Types model)
# Uses detect-entity-type task to resolve paths for any entity depth
detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
manifest_file: '{project-root}/docs/manifest.yaml'

# Entity-resolved paths (populated by detect-entity-type task)
# Supports: Constitution, Infrastructure Module, Strategic Container, Coordination Unit, Business Module
entity_type: '' # Detected: constitution, infrastructure_module, strategic_container, coordination_unit, business_module
output_folder_resolved: '' # e.g., "docs/platform/core-api/" or "docs/strategy/pulse/dashboard/"
parent_output_folder: '' # Parent entity path for parent-level context
module_code_path: '' # Resolved from manifest.yaml (e.g., "services/core-api")

# SSOT Atom System Integration
# Atoms provide authoritative requirements, decisions, and interfaces
atoms_dir: '{project-root}/docs/_atoms'
atom_search_script: '{project-root}/scripts/atoms/atom-search.ts'

# Sprint artifacts at entity level
sprint_artifacts: '{output_folder_resolved}sprint-artifacts'
sprint_status: '{sprint_artifacts}/sprint-status.yaml'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/4-implementation/code-review'
instructions: '{installed_path}/instructions.md'
validation: '{installed_path}/checklist.md'
template: false

variables:
  story_dir: '{sprint_artifacts}'
  tech_spec_search_dir: '{output_folder_resolved}'
  tech_spec_glob_template: 'tech-spec-epic-{{epic_num}}*.md'
  # Entity-aware architecture search (entity + parent chain)
  arch_docs_search_dirs: |
    - "{output_folder_resolved}"
    - "{parent_output_folder}"
    - "{base_output_folder}/platform/"
  arch_docs_file_names: |
    - architecture.md
  backlog_file: '{output_folder_resolved}backlog.md'
  update_epic_followups: true
  epic_followups_section_title: 'Post-Review Follow-ups'

  # Atom integration variables
  atom_entity_filter: '' # Set based on module (e.g., "SHL", "API")
  validate_atom_compliance: true # Check implementation against atom constraints

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the specific epic needed for this story review
# Uses output_folder_resolved from detect-entity-type task (Five Entity Types model)
input_file_patterns:
  architecture:
    description: 'System architecture for review context'
    whole: '{output_folder_resolved}*architecture*.md'
    sharded: '{output_folder_resolved}*architecture*/*.md'
    parent_fallback: '{parent_output_folder}*architecture*.md'
    load_strategy: 'FULL_LOAD'
  ux_design:
    description: 'UX design specification (if UI review)'
    whole: '{output_folder_resolved}*ux*.md'
    sharded: '{output_folder_resolved}*ux*/*.md'
    parent_fallback: '{parent_output_folder}*ux*.md'
    load_strategy: 'FULL_LOAD'
  epics:
    description: 'Epic containing story being reviewed'
    whole: '{output_folder_resolved}*epic*.md'
    sharded_index: '{output_folder_resolved}*epic*/index.md'
    sharded_single: '{output_folder_resolved}*epic*/epic-{{epic_num}}.md'
    load_strategy: 'SELECTIVE_LOAD'
  document_project:
    description: 'Brownfield project documentation (optional)'
    sharded: '{output_folder_resolved}index.md'
    load_strategy: 'INDEX_GUIDED'
  atoms:
    description: 'SSOT atoms referenced in story for compliance validation'
    search_command: 'pnpm exec tsx {atom_search_script} --entity {atom_entity_filter}'
    load_strategy: 'ON_DEMAND'

standalone: true
