# Epic Tech Context Validation Workflow
name: validate-epic-tech-context
description: 'Validates an epic technical context document against BMAD standards, ensuring completeness, accuracy, and alignment with PRD and architecture.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
date: system-generated

# Federated entity detection (Five Entity Types model)
detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
select_entity_task: '{project-root}/.bmad/bmm/tasks/select-entity.xml'
manifest_file: '{project-root}/docs/manifest.yaml'

# Entity-resolved paths
entity_type: ''
output_folder_resolved: ''
parent_output_folder: ''

# Sprint artifacts at entity level
sprint_artifacts: '{output_folder_resolved}sprint-artifacts'

# Epic tech context location (parameterized by epic_id)
epic_id: runtime-captured
epic_tech_context_path: '{sprint_artifacts}/tech-spec-epic-{{epic_id}}.md'

# Reference source documents for validation
prd_path: '{output_folder_resolved}prd.md'
architecture_path: '{output_folder_resolved}architecture.md'
epics_path: '{output_folder_resolved}epics.md'

# Reference base workflow for checklist
base_workflow: '{project-root}/.bmad/bmm/workflows/4-implementation/epic-tech-context'
base_checklist: '{base_workflow}/checklist.md'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/4-implementation/validate-epic-tech-context'
instructions: '{installed_path}/instructions.md'
checklist: '{installed_path}/checklist.md'
validation_report_template: '{installed_path}/validation-report-template.md'

# Output configuration
default_output_file: '{sprint_artifacts}/epic-tech-context-validation-{{epic_id}}-{{date}}.md'

standalone: true
