# Story Ready Workflow (SM Agent)
name: story-ready
description: "Marks a drafted story as ready for development and moves it from TODO → IN PROGRESS in the status file. Simple status-update workflow with no searching required."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
base_output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module isolation variables (Phase 2)
# Inherited from agent session - agents prompt for module selection at startup
manifest_file: "{project-root}/docs/manifest.yaml"
current_category: "" # Inherited from agent session (e.g., "platform")
current_module: "" # Inherited from agent session (e.g., "core-api")

# Module-scoped output paths
output_folder: "{base_output_folder}/{{current_category}}/{{current_module}}"
sprint_artifacts: "{output_folder}/sprint-artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/4-implementation/story-ready"
instructions: "{installed_path}/instructions.md"

# Variables and inputs
variables:
  story_dir: "{config_source}:sprint_artifacts"

standalone: true
