# Validate Domain PRD Workflow
name: validate-domain-prd
description: "Validate a Category/Subcategory/Module PRD against the Federated Requirements Model"
author: "BMad Builder"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Federated hierarchy support (from agent level-selection)
output_folder_resolved: "{output_folder_resolved}"
constitution_path: "{constitution_path}"
current_level: "{current_level}"
current_level_name: "{current_level_name}"
current_category: "{current_category}"
current_subcategory: "{current_subcategory}"
current_module: "{current_module}"

# Workflow components
installed_path: "{project-root}/.bmad/custom/modules/federated-validation/workflows/validate-domain-prd"
instructions: "{installed_path}/instructions.md"
validation: "{project-root}/.bmad/custom/modules/federated-validation/checklists/domain-prd-checklist.md"

# Constitution reference (for inheritance checking)
constitution: "{project-root}/docs/prd.md"

# Target file (determined by agent's level selection)
target_file: "{output_folder_resolved}/prd.md"

# Output
report_template: "{project-root}/.bmad/custom/modules/federated-validation/templates/validation-report.md"
default_output_file: "{project-root}/docs/proposals/validation-reports/domain-prd-validation-{current_level_name}-{date}.md"

# Validation patterns
validation_rules:
  frontmatter:
    required_fields:
      - level: ["category", "subcategory", "module"]
      - doc_type: "domain_prd"
      - parent: "docs/prd.md"

  content:
    must_contain:
      - pattern: "FR-[A-Z]+-\\d{3}"
        description: "Functional Requirements with scope prefix"
        minimum: 1

    should_contain:
      - pattern: "Inherits.*PR-\\d{3}"
        description: "Reference to inherited Platform Requirements"
      - pattern: "Implements.*IC-\\d{3}"
        description: "Declaration of implemented Integration Contracts"

standalone: true
template: false
