# Architecture Creation Router Workflow
name: create-architecture
description: "Smart router that detects entity type and dispatches to the appropriate architecture creation workflow (create-system-architecture or create-domain-architecture)."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Shared tasks
detect_entity_task: "{project-root}/.bmad/bmm/tasks/detect-entity-type.xml"

# Target workflows
system_architecture_workflow: "{project-root}/.bmad/bmm/workflows/3-solutioning/create-system-architecture/workflow.yaml"
domain_architecture_workflow: "{project-root}/.bmad/bmm/workflows/3-solutioning/create-domain-architecture/workflow.yaml"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/3-solutioning/create-architecture"
instructions: "{installed_path}/instructions.md"

template: false
standalone: true
