# Architecture Creation Workflow
name: create-architecture
description: 'Create Architecture documents for any entity type. Uses entity-first detection to determine context and adapts template/validation based on entity type (Constitution, Infrastructure Module, Strategic Container, Coordination Unit, Business Module).'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
project_name: '{config_source}:project_name'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
user_skill_level: '{config_source}:user_skill_level'
date: system-generated

# Entity-first detection - these are SET AT RUNTIME by select-entity task
# DO NOT hardcode - workflow will invoke select-entity to populate these
entity_type: '{entity_type}'
entity_type_display: '{entity_type_display}'
fr_prefix: '{fr_prefix}'
output_folder_resolved: '{output_folder_resolved}'
constitution_path: '{constitution_path}'
parent_prd_path: '{parent_prd_path}'
parent_architecture_path: '{parent_architecture_path}'
entity_code: '{entity_code}'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/3-solutioning/create-architecture'
instructions: '{installed_path}/instructions.md'

# Templates - selected based on entity_type at runtime
templates:
  constitution: '{installed_path}/constitution-architecture-template.md'
  domain: '{installed_path}/domain-architecture-template.md'

# Shared resources
decision_catalog: '{installed_path}/decision-catalog.yaml'
architecture_patterns: '{installed_path}/architecture-patterns.yaml'
pattern_categories: '{installed_path}/pattern-categories.csv'

# Checklists and Validation - selected based on entity_type at runtime
checklists:
  constitution: '{project-root}/.bmad/bmm/checklists/constitution-architecture-checklist.md'
  domain: '{project-root}/.bmad/bmm/checklists/domain-architecture-checklist.md'
validation:
  required: true
  on_fail: 'warn_and_offer_fix'

# Shared tasks
select_entity_task: '{project-root}/.bmad/bmm/tasks/select-entity.xml'
detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
frontmatter_task: '{project-root}/.bmad/bmm/tasks/generate-frontmatter.xml'
save_task: '{project-root}/.bmad/bmm/tasks/save-with-checkpoint.xml'
validate_inheritance_task: '{project-root}/.bmad/bmm/tasks/validate-inheritance.xml'

# Input file patterns - paths resolved after entity detection
input_file_patterns:
  entity_prd:
    description: 'PRD for the selected entity - required'
    whole: '{output_folder_resolved}prd.md'
    load_strategy: 'FULL_LOAD'

  parent_architecture:
    description: 'Parent architecture (for inheritance validation)'
    whole: '{parent_architecture_path}'
    load_strategy: 'FULL_LOAD'
    optional: true

  existing_architecture:
    description: 'Existing architecture (if updating)'
    whole: '{output_folder_resolved}architecture.md'
    load_strategy: 'FULL_LOAD'
    optional: true

  ux_design:
    description: 'UX Design specification (optional)'
    whole: '{output_folder_resolved}ux-design.md'
    load_strategy: 'FULL_LOAD'
    optional: true

# Output files
status_file: '{output_folder}/bmm-workflow-status.yaml'
default_output_file: '{output_folder_resolved}architecture.md'

standalone: true
