# Epics Amendment Router Workflow
name: amend-epics
description: "Smart router that detects entity type and dispatches to the appropriate epics amendment workflow."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Shared tasks
detect_entity_task: "{project-root}/.bmad/bmm/tasks/detect-entity-type.xml"

# Target workflows
system_amend_workflow: "{project-root}/.bmad/bmm/workflows/3-solutioning/amend-system-epics/workflow.yaml"
domain_amend_workflow: "{project-root}/.bmad/bmm/workflows/3-solutioning/amend-domain-epics/workflow.yaml"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/3-solutioning/amend-epics"
instructions: "{installed_path}/instructions.md"

template: false
standalone: true
