# Domain Architecture Validation Workflow
name: validate-domain-architecture
description: 'Validate domain architecture documents against Constitution, parent architecture, and entity-specific requirements.'
author: 'BMad'

config_source: '{project-root}/.bmad/bmm/config.yaml'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

entity_type: '{entity_type}'
entity_type_display: '{entity_type_display}'
output_folder_resolved: '{output_folder_resolved}'
architecture_path: '{output_folder_resolved}architecture.md'
parent_architecture_path: '{parent_architecture_path}'
constitution_architecture_path: 'docs/platform/architecture.md'

installed_path: '{project-root}/.bmad/bmm/workflows/3-solutioning/validate-domain-architecture'
instructions: '{installed_path}/instructions.md'

detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
validate_inheritance_task: '{project-root}/.bmad/bmm/tasks/validate-inheritance.xml'

checklist_infrastructure: '{project-root}/.bmad/bmm/checklists/infrastructure-architecture-checklist.md'
checklist_strategic: '{project-root}/.bmad/bmm/checklists/strategic-architecture-checklist.md'
checklist_coordination: '{project-root}/.bmad/bmm/checklists/coordination-architecture-checklist.md'
checklist_business: '{project-root}/.bmad/bmm/checklists/business-architecture-checklist.md'

# Validation - schema resolved based on entity type
validation:
  schema_map:
    infrastructure_module: '{project-root}/.bmad/bmm/checklists/infrastructure-architecture-checklist.md'
    strategic_container: '{project-root}/.bmad/bmm/checklists/strategic-architecture-checklist.md'
    coordination_unit: '{project-root}/.bmad/bmm/checklists/coordination-architecture-checklist.md'
    business_module: '{project-root}/.bmad/bmm/checklists/business-architecture-checklist.md'
  strict: true
  min_pass_rate: 80
  inheritance_required: true

validation_report_path: '{output_folder_resolved}validation-reports/architecture-validation-{date}.md'

template: false
standalone: true
