# UX Design Validation Router Workflow
name: validate-ux
description: "Smart router that detects entity type and dispatches to the appropriate UX validation workflow (validate-system-ux or validate-domain-ux)."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Shared tasks
detect_entity_task: "{project-root}/.bmad/bmm/tasks/detect-entity-type.xml"

# Target workflows
system_validate_workflow: "{project-root}/.bmad/bmm/workflows/3-solutioning/validate-system-ux/workflow.yaml"
domain_validate_workflow: "{project-root}/.bmad/bmm/workflows/3-solutioning/validate-domain-ux/workflow.yaml"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/3-solutioning/validate-ux"
instructions: "{installed_path}/instructions.md"

template: false
standalone: true
