# Validate Constitution PRD Workflow
name: validate-constitution
description: "Validate the System-level PRD (Constitution) against the Federated Requirements Model"
author: "BMad Builder"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Federated hierarchy support (from agent level-selection)
output_folder_resolved: "{output_folder_resolved}"
constitution_path: "{constitution_path}"
current_level: "{current_level}"
current_level_name: "{current_level_name}"

# Workflow components
installed_path: "{project-root}/.bmad/custom/modules/federated-validation/workflows/validate-constitution"
instructions: "{installed_path}/instructions.md"
validation: "{project-root}/.bmad/custom/modules/federated-validation/checklists/constitution-checklist.md"

# Target file (the Constitution PRD)
target_file: "{project-root}/docs/prd.md"

# Output
report_template: "{project-root}/.bmad/custom/modules/federated-validation/templates/validation-report.md"
default_output_file: "{project-root}/docs/proposals/validation-reports/constitution-validation-{date}.md"

# Validation patterns
validation_rules:
  frontmatter:
    required_fields:
      - level: "system"
      - doc_type: "constitution"

  content:
    must_contain:
      - pattern: "PR-\\d{3}"
        description: "Platform Requirements with proper numbering"
        minimum: 5
      - pattern: "IC-\\d{3}"
        description: "Integration Contracts with proper numbering"
        minimum: 3

    must_not_contain:
      - pattern: "FR-[A-Z]+-\\d{3}"
        description: "Functional Requirements (belong in domain PRDs)"

standalone: true
template: false
