# System UX Design Workflow (Constitution)
name: create-system-ux
description: 'Create or update the System UX Design (Constitution) establishing platform-wide UX principles, design system foundation, and interaction paradigms that ALL entities inherit.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
project_name: '{config_source}:project_name'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
user_skill_level: '{config_source}:user_skill_level'
date: system-generated

# Federated hierarchy - Constitution is fixed
entity_type: constitution
entity_type_display: 'Constitution'
output_folder_resolved: '{project-root}/docs/platform/'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/3-solutioning/create-system-ux'
instructions: '{installed_path}/instructions.md'

# Templates
ux_template: '{installed_path}/constitution-ux-template.md'

# Checklists and Validation
checklist: '{project-root}/.bmad/bmm/checklists/constitution-ux-checklist.md'
validation:
  schema: '{checklist}'
  required: true
  on_fail: 'warn_and_offer_fix'

# Shared tasks
detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
frontmatter_task: '{project-root}/.bmad/bmm/tasks/generate-frontmatter.xml'
save_task: '{project-root}/.bmad/bmm/tasks/save-with-checkpoint.xml'
validate_inheritance_task: '{project-root}/.bmad/bmm/tasks/validate-inheritance.xml'

# Input file patterns - Constitution references product brief and PRD
input_file_patterns:
  product_brief:
    description: 'Product vision and goals'
    whole: '{output_folder_resolved}product-brief.md'
    sharded: '{output_folder_resolved}product-brief/index.md'
    load_strategy: 'FULL_LOAD'

  constitution_prd:
    description: 'System PRD for requirement alignment'
    whole: '{output_folder_resolved}prd.md'
    load_strategy: 'FULL_LOAD'

  constitution_architecture:
    description: 'System Architecture for technical context'
    whole: '{output_folder_resolved}architecture.md'
    load_strategy: 'FULL_LOAD'

  existing_ux:
    description: 'Existing Constitution UX (if updating)'
    whole: '{output_folder_resolved}ux-design.md'
    load_strategy: 'FULL_LOAD'

# Output files
status_file: '{output_folder}/bmm-workflow-status.yaml'
default_output_file: '{output_folder_resolved}ux-design.md'
color_themes_html: '{output_folder_resolved}ux-color-themes.html'
design_directions_html: '{output_folder_resolved}ux-design-directions.html'

standalone: true
