# Validate Code Review Workflow
name: validate-code-review
description: 'Validates that a code review was thorough and complete. Checks AC coverage, task verification, evidence quality, and review standards compliance.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/.bmad/bmm/config.yaml'
base_output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
date: system-generated

# Federated entity detection (Five Entity Types model)
detect_entity_task: '{project-root}/.bmad/bmm/tasks/detect-entity-type.xml'
manifest_file: '{project-root}/docs/manifest.yaml'

# Entity-resolved paths
entity_type: ''
output_folder_resolved: ''
parent_output_folder: ''

# Sprint artifacts
sprint_artifacts: '{output_folder_resolved}sprint-artifacts'
sprint_status: '{sprint_artifacts}/sprint-status.yaml'

# Workflow components
installed_path: '{project-root}/.bmad/bmm/workflows/4-implementation/validate-code-review'
instructions: '{installed_path}/instructions.md'
checklist: '{installed_path}/checklist.md'

# Related workflows
code_review_workflow: '{project-root}/.bmad/bmm/workflows/4-implementation/code-review/workflow.yaml'

variables:
  story_dir: '{sprint_artifacts}'
  story_file: '' # Story with review to validate

  # Validation criteria
  require_ac_coverage: true # Must have AC validation table
  require_task_verification: true # Must have task verification table
  require_evidence: true # Must have file:line evidence
  require_action_items: true # Must have actionable items (if issues found)

  # Thresholds
  min_ac_coverage_percent: 100 # All ACs must be validated
  min_task_verification_percent: 100 # All completed tasks verified

  # Output
  generate_report: true

standalone: true
