# PRD Creation Router Workflow
name: create-prd
description: "Smart router that detects entity type from context or user input, then dispatches to the appropriate PRD creation workflow (create-system-prd or create-domain-prd)."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated

# Shared tasks
detect_entity_task: "{project-root}/.bmad/bmm/tasks/detect-entity-type.xml"

# Target workflows
system_prd_workflow: "{project-root}/.bmad/bmm/workflows/2-plan-workflows/create-system-prd/workflow.yaml"
domain_prd_workflow: "{project-root}/.bmad/bmm/workflows/2-plan-workflows/create-domain-prd/workflow.yaml"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/2-plan-workflows/create-prd"
instructions: "{installed_path}/instructions.md"

# This is a router - no template
template: false
standalone: true
